# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ 'main' ]
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        id: check-branch
        continue-on-error: false
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} =~ Team[0-9]*$ ]]; then
              echo ::set-output name=match::true
          else
            exit 1
          fi
      - name: step result
        run: echo ${{steps.check-branch.conclusion}}
      - name: Request flag2
        if: steps.check-branch.outputs.match == 'true'
        run: |
          curl -r POST "https://${HOSTNAME}/prod/pets" -H "${HEADER}" --data-raw '{"type" : "cat","price" : 123.11}' | jq '.pet'
        env:
          HOSTNAME: 'wsqkd3gvmk.execute-api.us-east-1.amazonaws.com'
          TOKEN: 'TmljZSB0cnksIGJ1dCB5b3UgbXVzdCBjb21wbGV0ZSB0aGUgY2hhbGxlbmdl'
          HEADER: 'Content-Type: application/json'
          STEP: 'GithubActions'
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: |
            --json
            --severity-threshold=high
            --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
